# Generated by Django 3.2 on 2021-04-17 22:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0002_rename_listings_listing'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='price',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
