# Generated by Django 3.1.8 on 2021-04-19 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0007_auto_20210419_0935'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='order_by',
            field=models.IntegerField(default=0),
        ),
    ]
