# Generated by Django 3.1.8 on 2021-04-19 19:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0009_auto_20210419_1902'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='contact_name',
            field=models.CharField(max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='listing',
            name='contact_number',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='listing',
            name='email_address',
            field=models.CharField(max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='listing',
            name='listing_name',
            field=models.CharField(max_length=250, null=True),
        ),
    ]
