# Generated by Django 3.1.8 on 2021-04-19 19:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0010_auto_20210419_1908'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='lease',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='listing',
            name='price',
            field=models.CharField(max_length=250, null=True),
        ),
    ]
