# Generated by Django 3.1.8 on 2021-04-19 19:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0011_auto_20210419_1909'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='contact_number',
            field=models.CharField(max_length=12, null=True),
        ),
    ]
